export const DATA =[
    {
        id:0,
        title: 'telefono',
        price: 100,
        desc: 'descripcion1',
        img: '/assets/images/products/img1.png'
    },
    {    id:1,
        title: 'colchon',
        price: 100,
        desc: 'descripcion3',
        img: '/assets/images/products/img3.jpg'},
    {    id:2,
        title: 'play 5',
        price: 100,
        desc: 'descripcion2',
        img: '/assets/images/products/img2.jpg'},
        {
            id:3,
            title: 'telefono',
            price: 100,
            desc: 'descripcion1',
            img: '/assets/images/products/img1.png'
        },
        {    id:4,
            title: 'colchon',
            price: 100,
            desc: 'descripcion3',
            img: '/assets/images/products/img3.jpg'},
        {    id:5,
            title: 'play 5',
            price: 100,
            desc: 'descripcion2',
            img: '/assets/images/products/img2.jpg'},
            {
                id:6,
                title: 'telefono',
                price: 100,
                desc: 'descripcion1',
                img: '/assets/images/products/img1.png'
            },
            {    id:7,
                title: 'colchon',
                price: 100,
                desc: 'descripcion3',
                img: '/assets/images/products/img3.jpg'},
            {    id:8,
                title: 'play 5',
                price: 100,
                desc: 'descripcion2',
                img: '/assets/images/products/img2.jpg'},
                {
                    id:9,
                    title: 'telefono',
                    price: 100,
                    desc: 'descripcion1',
                    img: '/assets/images/products/img1.png'
                },
                {    id:10,
                    title: 'colchon',
                    price: 100,
                    desc: 'descripcion3',
                    img: '/assets/images/products/img3.jpg'}
]
